---
apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: "example"
spec:
  storageClassDevices:
    - storageClassName: "foobar"
      volumeMode: Filesystem
      fsType: ext4
      devicePaths:
        - /dev/vde
        - /dev/vdf
