apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
  name: localdisks
  namespace: openshift-local-storage
spec:
  maxDeviceCount: 5
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - ip-10-0-130-127
  storageClassName: local-sc
  volumeMode: Block
  deviceInclusionSpec:
    deviceTypes:
      - disk
    deviceMechanicalProperties:
      - Rotational
      - NonRotational
    minSize: 5Gi
    maxSize: 90Gi