apiVersion: v1
data:
  storageClassMap: |
    local-sc:
      fstype: xfs
      hostDir: /mnt/local-storage/local-sc
      mountDir: /mnt/local-storage/local-sc
      volumeMode: Filesystem
kind: ConfigMap
metadata:
  creationTimestamp: "2019-06-28T02:17:43Z"
  labels:
    app: local-volume-provisioner-local-disks
    local.storage.openshift.io/owner-name: local-disks
    local.storage.openshift.io/owner-namespace: local-storage
  name: local-disks-local-provisioner-configmap
  namespace: local-storage
  ownerReferences:
  - apiVersion: local.storage.openshift.io/v1
    controller: true
    kind: LocalVolume
    name: local-disks
    uid: e96db637-994a-11e9-aa0d-5254002691cd
  resourceVersion: "1929954"
  selfLink: /api/v1/namespaces/local-storage/configmaps/local-disks-local-provisioner-configmap
  uid: e9771a23-994a-11e9-aa0d-5254002691cd
